name-template: "v$NEXT_PATCH_VERSION 🌈"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels: 
      - "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  # What's changed (changelog)
  $CHANGES
  
  ## 👍 Thanks to
  $CONTRIBUTORS
