config:
  dockerfile: .woloxci/Dockerfile
  project_name: mario


steps:
  copy_node_modules:
    - cp -r $NODE_PATH/ ./
  lint:
    - npm run lint
  test:
    - npm run test

environment:
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
  SECRET_KEY: secret_key
  REDIS_URL: redis://redis
  REDIS_NAME: 1
  REDIS_NAME_DEV: 2
  REDIS_NAME_TEST: 3
